version: '3'
services:
  backend:
    build: 
      dockerfile: ./dockerfile-backend
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    volumes:
      - .:/serv  # Adjust the volume path based on your project structure

  frontend:
    build:
      dockerfile: ./dockerfile-frontend
      context: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app  # Adjust the volume path based on your project structure

  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: 'CRT-Data'