
FROM node:lts-alpine AS build-stage


WORKDIR /app

COPY package.json ./

RUN npm install


ENTRYPOINT [ "./entrypoint.sh" ]

COPY .env ./


COPY . .


COPY src ./src



RUN npm run build

FROM nginx:latest AS production-stage
ARG PORT=5173
ENV PORT=$PORT

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf ./nginx.conf
EXPOSE $PORT


CMD ["nginx", "-g", "daemon off;"]