version: '3'
services:
  backend:
    build: 
      dockerfile: ./dockerfile-backend
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
    volumes:
      - .:/serv  

  frontend:
    build:
      dockerfile: ./dockerfile-frontend
      context: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app  

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: 'CRT-Data'
    ports:
    - "27017:27017"
    volumes:
    - ./mongoscripts/01-init-users.js:/docker-entrypoint-initdb.d/01-init-users.js:ro