
FROM node:lts-alpine

WORKDIR /serv

COPY package*.json ./

RUN npm install

RUN npm install esbuild-wasm

RUN npm install -g concurrently
ENTRYPOINT [ "./entrypoint.sh" ]

COPY .env ./

COPY SSL/ SSL/

COPY . .


COPY server/ server/

EXPOSE 3000


CMD ["npm", "run", "start"]