
FROM node:lts-alpine AS build-stage


WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm install esbuild-wasm

RUN npm install -g concurrently
ENTRYPOINT [ "./entrypoint.sh" ]

COPY .env ./


COPY . .


COPY src ./src


EXPOSE 5173


RUN npm run build

FROM nginx:latest AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]